# This is the name of the workflow
name: Integrate Actions

# Define the triggers that will activate the actions
on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull request to the master branch

# Define the jobs to run
jobs:
  test_pull_request:
    # This job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # Run tests for multiple Node.js versions using a matrix
    strategy:
      matrix:
        node-version: [16.x, 18.x]  # Test with Node.js versions 16.x and 18.x

    steps:
      # Step 1: Check out the code from the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js with the version from the matrix
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies using npm ci
      - run: npm ci

      # Step 4: Run tests using npm test
      - run: npm test
